prometheus:       # Prometheus Config section
  prom_img: prom/prometheus:latest
  prom_label: prom
  prom_mem_limit: 500m
  prom_mem_res: 450m
  prom_command: --config.file=/etc/prometheus/prometheus.yml
  prom_config: sckl-scripts/prometheus.yml      # Relative to base dir path
  prom_ports: {'9091': '9090'}
influxdb:
  ifxdb_img: influxdb:1.7
  ifxdb_label: influxdb
  ifxdb_command: ''
  ifxdb_mem_limit: 500m
  ifxdb_mem_res: 450m
  ifxdb_db: ngcdi_metrics
  ifxdb_env: {INFLUXDB_DB: ngcdi_metrics}
  ifxdb_port: '8086'
cadvisor:
  cadvisor_img: google/cadvisor:latest
  cadvisor_label: cadvisor
  cadvisor_mem_limit: 350m
  cadvisor_mem_res: 300m
  cadvisor_command: ''
  cadvisor_env: {storage_driver: influxdb, storage_driver_db: ngcdi_metrics, storage_driver_host: influxdb1:8086}
  cadvisor_vols: {/: {bind: /rootfs, mode: ro}, /var/run: {bind: /var/run, mode: rw},
    /sys: {bind: /sys, mode: ro}, /snap/docker/: {bind: /var/lib/docker, mode: ro}}
  cadvisor_ports: {'8080': '9080'}     # 9080 to avoid clash with sdn controller
grafana:
  grafana_img: ngcdi/grafana:5.4.3
  grafana_label: grafana
  grafana_mem_limit: 350m
  grafana_mem_res: 300m
  grafana_command: ''
  grafana_env: {GF_SECURITY_ADMIN_PASSWORD: password}
  grafana_vols: {/home/mep53/workspace/ngcdi-cam/sckl-grafana/dashboards/: {
      bind: /var/lib/grafana/dashboards, mode: ro}}
  grafana_ports: {'3000': '3000'}
